// Auto-generated by vite.config.js steamNewsData plugin
export const STEAM_NEWS_ITEMS = [
  {
    image: "https://cdn.fastly.steamstatic.com/steam/apps/367270/header.jpg",
    title: "Now Available on Steam - Angels Fall First, 10% off!",
    date: "July 11, 2026"
  },
  {
    image: "https://cdn.fastly.steamstatic.com/steam/apps/513710/header.jpg",
    title: "Now Available on Steam - SCUM",
    date: "June 17, 2025"
  },
  {
    image: "https://cdn.fastly.steamstatic.com/steam/apps/690830/header.jpg",
    title: "Now Available on Steam - Foundation, 25% off!",
    date: "January 31, 2025"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/352720/header.jpg",
    title: "Now Available on Steam - The Universim",
    date: "January 22, 2024"
  },
  {
    image: "https://cdn.akamai.steamstatic.com/steam/apps/517670/header.jpg",
    title: "Now Available on Steam - Cowbots and Aliens",
    date: "December 25, 2023"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/479010/header.jpg",
    title: "Now Available on Steam - Kodon",
    date: "December 10, 2023"
  },
  {
    image: "https://cdn.akamai.steamstatic.com/steam/apps/1355090/header.jpg",
    title: "Now Available on Steam - RAILGRADE, 25% off!",
    date: "October 13, 2023"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/758870/header.jpg",
    title: "Now Available on Steam - Kynseed, 10% off!",
    date: "December 6, 2022"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/611500/header.jpg",
    title: "Now Available on Steam - Quake Champions",
    date: "August 18, 2022"
  },
  {
    image: "https://cdn.akamai.steamstatic.com/steam/apps/911430/header.jpg",
    title: "Now Available on Steam - Good Company, 20% off!",
    date: "June 21, 2022"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg",
    title: "Now Available on Steam - Raft, 15% off!",
    date: "June 20, 2022"
  },
  {
    image: "https://cdn.akamai.steamstatic.com/steam/apps/860890/header.jpg",
    title: "Now Available on Steam - Factory Town",
    date: "November 17, 2021"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1276790/header.jpg",
    title: "Now Available on Steam - Ruined King: A League of Legends Story™",
    date: "November 16, 2021"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/910490/header.jpg",
    title: "Now Available on Steam - Killsquad, 20% off!",
    date: "October 21, 2021"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/469600/header.jpg",
    title: "Now Available on Steam - Legion TD 2 - Multiplayer Tower Defense",
    date: "October 1, 2021"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/471710/header.jpg",
    title: "Now Available on Steam - Rec Room",
    date: "September 2, 2021"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/597170/header.jpg",
    title: "Now Available on Steam - Clone Drone in the Danger Zone, 15% off!",
    date: "July 27, 2021"
  },
  {
    image: "https://cdn.akamai.steamstatic.com/steam/apps/508440/header.jpg",
    title: "Now Available on Steam - Totally Accurate Battle Simulator",
    date: "April 1, 2021"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1427650/header.jpg",
    title: "New DLC Available - ROMANCE OF THE THREE KINGDOMS XIV: Diplomacy and Strategy Expansion Pack, 10% off!",
    date: "December 10, 2020"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1054690/header.jpg",
    title: "Now Available on Steam - Dreadlands, 20% off!",
    date: "November 9, 2020"
  },
  {
    image: "https://steamcdn-a.akamaihd.net/steam/apps/824570/header.jpg",
    title: "Now Available on Steam - Kine, 34% off!",
    date: "October 19, 2020"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/881100/header.jpg",
    title: "Now Available on Steam - Noita, 20% off!",
    date: "October 15, 2020"
  },
  {
    image: "https://steamcdn-a.akamaihd.net/steam/apps/393380/header.jpg",
    title: "Now Available on Steam - Squad",
    date: "September 23, 2020"
  },
  {
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/978180/header.jpg",
    title: "Now Available on Steam - Stay Silent",
    date: "September 17, 2020"
  },
  {
    image: "https://steamcdn-a.akamaihd.net/steam/apps/632360/header.jpg",
    title: "Now Available on Steam - Risk of Rain 2",
    date: "August 11, 2020"
  },
  {
    image: "https://steamcdn-a.akamaihd.net/steam/apps/1072710/header.jpg",
    title: "Now Available on Steam - Soviet Jump Game",
    date: "July 16, 2020"
  },
  {
    image: "https://steamcdn-a.akamaihd.net/steam/news/62557/social_media_share.jpg?t=1592505828",
    title: "Weekend Deal - The Elder Scrolls Franchise, 60-70% Off",
    date: "June 18, 2020"
  },
  {
    image: "https://steamcdn-a.akamaihd.net/steam/apps/1151340/header.jpg",
    title: "Free Weekend - Fallout 76",
    date: "May 14, 2020"
  },
  {
    image: "https://media.st.dl.pinyuncloud.com/steam/apps/548430/header.jpg",
    title: "Now Available on Steam - Deep Rock Galactic",
    date: "May 13, 2020"
  },
  {
    image: "https://steamcdn-a.akamaihd.net/steam/apps/1295160/header.jpg",
    title: "Now Available on Steam - Resident Evil 3 Special Soundtrack",
    date: "May 7, 2020"
  }
];
